### ISSUE TITLE
Screenshot of your phone homescreen

### ISSUE THREAD

**Issue by AchoArnold** [thexavismith/ama#2]

**Comment by thexavismith** [comment]
Hi @AchoArnold! Thanks for the question! Here's a picture of my current homescreen. 

![2016-09-18 14 57 18](https://cloud.githubusercontent.com/assets/1326249/18618629/5d8aca1e-7db0-11e6-913c-1b3cdf92f27e.png)

**Comment by AchoArnold** [comment]
Thanks 👍
