### ISSUE TITLE
Tools that you use for Designing?

### ISSUE THREAD

**Issue by arjunmayilvaganan** [thexavismith/ama#3]
What are some of the tools that you use to create your web designs?

**Comment by thexavismith** [comment]
Great question @arjunmayilvaganan! Sorry for the super late response! I must've missed this!

Here are the tools I use:

- **[Atom](https://atom.io/)** - My text editor. Atom has a very active community with lots of packages (or plugins). They've also made it very easy to keep your config in version control which is very important to me. [Here's my Atom config](https://github.com/smithtimmytim/atom-config).
- **[Hyper](https://hyper.is/)** - My preferred terminal. Most OSs have a terminal that comes wiith it, but as a Mac user, I really like Hyper. Easily extendible and customizable.
- **[Sketch](https://www.sketchapp.com/)** - This is what I use to create layouts and mockups. Sketch is a great tool, and is actively being developed.

And that's it!
