### ISSUE TITLE
What are your favorite comics?

### ISSUE THREAD

**Issue by elderfo** [thexavismith/ama#5]
I just saw that you are a comic fan! What are some of your favorites?

I was an indy guy for years, then got hooked DC's new 52 and eventually Marvel NOW. I am not reading much these days, a few on Comixology here and there. I'm still very much an indy fan (wait, is Image still considered indy?)

**Comment by thexavismith** [comment]
@elderfo Thanks for another great question! I actually wrote about this recently: https://theboldreport.net/2016/05/going-back-to-comics/
